apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    helm.sh/chart: ingress-nginx-2.1.0
  name: nginx-ingress-controller-ingress-nginx-admission-patch
  namespace: nginx-namespace
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/component: admission-webhook
        app.kubernetes.io/instance: nginx-ingress-controller
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/version: 0.32.0
        helm.sh/chart: ingress-nginx-2.1.0
      name: nginx-ingress-controller-ingress-nginx-admission-patch
    spec:
      containers:
      - args:
        - patch
        - --webhook-name=nginx-ingress-controller-ingress-nginx-admission
        - --namespace=nginx-namespace
        - --patch-mutating=false
        - --secret-name=nginx-ingress-controller-ingress-nginx-admission
        - --patch-failure-policy=Fail
        image: jettech/kube-webhook-certgen:v1.2.0
        imagePullPolicy: IfNotPresent
        name: patch
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
      serviceAccountName: nginx-ingress-controller-ingress-nginx-admission
