apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt-cluster-issuer
  namespace: cert-manager-namespace
spec:
  acme:
    email: andersonciputra@gmail.com
    privateKeySecretRef:
      name: lets-encrypt-cluster-issuer-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
