apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: nginx-ingress-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 0.32.0
    helm.sh/chart: ingress-nginx-2.1.0
  name: nginx-ingress-controller-ingress-nginx
  namespace: nginx-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-controller-ingress-nginx
subjects:
- kind: ServiceAccount
  name: nginx-ingress-controller-ingress-nginx
  namespace: nginx-namespace
